Corr_2PCF:
   sfc_field: "./output/quijote8000_snap004_sfc.pkl"
   random: "uniform"
   binning_window: "ring"
   sampling:
      s:
         min: 0.0
         max: 180.0
         n: 46
      mu:
         min: 0.0
         max: 1.0
         n: 51
   threads: 8
   products: "xi"
   fout_path: "./output/quijote8000_snap004_2pcf_smu.pkl"
