SFCProjection:
   fin:
      path: "./data/quijote_halos/8000"
      format: "fof"
      reader_params:
         snapnum: 4
      #    redshift: 0.0
      #    fields:
      #       mass: "mass"
      #       vel_x: "vel_x"
      #       vel_y: "vel_y"
      #       vel_z: "vel_z"
      #       npart: "npart"
      # catalog_weight_key: null
      # field_value_key: null
   box_size: 1000
   J: 8
   wavelet_mode: "db2"
   wavelet_level: 10
   phi_resolution: 1024
   threads: 2
   save_particle_data: True
   particle_data_path: "./data/quijote_halos/8000/groups_004/group_tab_004.pos.npz"
   fout_path: "./output/quijote8000_snap004_sfc.pkl"
