Corr_3PCF:
   convols_data: "./output/quijote_sfc.pkl"
   convols_data1: ""
   convols_data2: ""
   convols_data3: ""
   particle_data1:
   fout_path: "./output/quijote_3pcf_rand1e7.pkl"
   window2:
      type: "sphere"
      len_args:
         R: 5
   window3:
      type: "sphere"
      len_args:
         R: 5
   r12: 20.0
   r13: 40.0
   n_theta: 20
   n_rot: 20
   # center: "particle"
   center: "random"
   products: "Q"
   n_rand: 10000000
   base_seed: 42
