Corr_2PCF:
   convols_data: "./output/quijote_sfc.pkl"
   random: "uniform"
   fout_path: "./output/quijote_2pcf.pkl"
   pair_window:
      type: "shell"
      len_args: ["R"]
      los_args: {}
      other_args: {}
      mapping: "s_to_R"
      kernel_mode: "octant"
   sampling:
      s:
         min: 1.0
         max: 150.0
         n: 30
   products: "xi"
