Corr_3PCF:
   sfc_field: "./output/quijote8000_snap004_sfc.pkl"
   random: "uniform"
   fout_path: "./output/quijote8000_snap004_3pcf_pcenter_nrot500.pkl"
   window2:
      type: "sphere"
      len_args:
         R: 5
   window3:
      type: "sphere"
      len_args:
         R: 5
   r12: 20.0
   r13: 40.0
   theta:
      theta_min: 0.0
      theta_max: 3.141592653589793
      n_theta: 20
   n_rot: 500
   center: "particle"
   threads: 8
   products: "Q"
   base_seed: 42
