Corr_2PCF:
   convols_data: "./output/quijote_sfc.pkl"
   fout_path: "./output/quijote_2pcf.pkl"
   pair_window:
      type: ""
      len_args: {}
      other_args: {}
   r_min: 1.0
   r_max: 150.0
   n_r: 30
   products: "xi"
