Corr_2PCF:
   convols_data: "./output/quijote8000_snap004_rsd_sfc.pkl"
   random: "./output/random_sfc.pkl"
   window:
      type: "sphere"
      len_args:
         R: 5
   pair_window:
      type: "ring"
      mapping: "rppi_to_RH"
   sampling:
      rp:
         min: 0.0
         max: 180.0
         n: 46
      pi:
         min: 0.0
         max: 180.0
         n: 46
   threads: 8
   products: "xi"
   fout_path: "./output/quijote8000_snap004_rsd_2pcf_rppi_sph5_with_random.pkl"
   # memory_strategy: "memory"
   # fout_path: "./output/quijote8000_snap004_rsd_2pcf_rppi_sph5_with_random_memory.pkl"
