SFCProjection:
   fin:
      path: "https://pyhermes.astroslacker.com/downloads/quijote_halos_8000_snap004.npz"
      format: "npz"
      download:
         cache_path: "./data/quijote_halos_8000_snap004.npz"
         sha256: "b2b4b8c2fb91fa857e21b43d943cc32a2c423ee7cf5d7f13dede608264b08ef6"
      catalog_weight_key: null
      field_value_key: null
   box_size: 1000.0
   J: 8
   wavelet_mode: "db2"
   wavelet_level: 10
   phi_resolution: 1024
   weight_normalization: "catalog"
   threads: 2
   save_particle_data: true
   particle_data_path: "./output/quijote8000_snap004_particles.npz"
   fout_path: "./output/quijote8000_snap004_sfc.pkl"
