Corr_3PCF_Multipole:
   sfc_field: "./output/quijote8000_snap004_sfc.pkl"
   random: "./output/random_sfc.pkl"
   window2:
      type: "sphere"
      len_args:
         R: 5
   window3:
      type: "sphere"
      len_args:
         R: 5
   binning_window12:
      type: "shell"
      len_args: {}
      other_args: {}
      mapping:
         R: "r12"
   binning_window13:
      type: "shell"
      len_args: {}
      other_args: {}
      mapping:
         R: "r13"
   sampling:
      r12: 20.0
      r13: 40.0
   l_max: 14
   gpu_device_id: 0
   execution_mode: "pair_mpi"
   threads: 4
   products: ["ddd_l", "zeta_l"]
   fout_path: "./output/quijote8000_snap004_3pcf_multipole_lmax14_with_random.pkl"
