SFCProjection:
   fin:
      path: "https://pyhermes.astroslacker.com/downloads/group_tab_004.0"
      format: "fof"
      download:
         cache_path: "./data/quijote_halos/8000/groups_004/group_tab_004.0"
         sha256: "4a1c6ca4f6747a70e9e552685226ecf5d678c6c97551e2caa7cc3883502eac85"
      catalog_weight_key: null
      field_value_key: null
   box_size: 1000.0
   J: 8
   wavelet_mode: "db2"
   wavelet_level: 10
   phi_resolution: 1024
   weight_normalization: "catalog"
   threads: 2
   save_particle_data: true
   particle_data_path: "./output/quijote8000_snap004_particles.npz"
   fout_path: "./output/quijote8000_snap004_sfc.pkl"
